const auth = require('../middleware/auth')
const { User, validate } = require('../models/user.model')
const express = require('express')
const profileMiddleware = require('../middleware/profiles')
const router = express.Router()
const upload = require('../middleware/upload')

router.post('/buyer', auth, profileMiddleware.setBuyerProfile)
router.get('/buyer', auth, profileMiddleware.getBuyerProfile)
router.post('/buyer/photo', [auth, upload], profileMiddleware.uploadBuyerPhoto)
router.post('/seller', auth, profileMiddleware.setSellerProfile)
router.get('/seller', auth, profileMiddleware.getSellerProfile)
router.post('/seller/photo', [auth, upload], profileMiddleware.uploadSellerPhoto)
router.get('/buyerPhoto/:filename',profileMiddleware.getImage)
module.exports = router
